/* Development only: editable JSON + vanilla source -> three deployment files. */
'use strict';
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '../..');
const SRC = path.join(ROOT, 'frontend/src/briefing');
const OUT = path.join(ROOT, 'frontend/briefing-fabrix');
const ACTIVE = path.join(ROOT, 'agent-workbench/case-design/active');
const contract = require('../../frontend/src/briefing/briefing-contract');
const wire = require('../../frontend/src/briefing/fabrix-briefing-contract');
const read = file => fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n');
const json = file => JSON.parse(read(file));

function inputs() {
  const dataDir = path.join(ACTIVE, 'display-data'), briefingDir = path.join(ACTIVE, 'briefing-json');
  // B = case customers with S1-S5 briefings, C = conversational-agent demo customers (customer data only).
  const customerFiles = fs.readdirSync(dataDir).filter(f => /^[BC]\d{2}-\d{2}\.json$/.test(f)).sort();
  const customers = customerFiles.map(f => {
    const customer = json(path.join(dataDir, f));
    if (customer.briefingMeta.caseId + '.json' !== f) throw new Error('Customer filename/caseId mismatch: ' + f);
    return customer;
  });
  const ids = customers.map(c => c.briefingMeta.caseId);
  if (new Set(ids).size !== ids.length || new Set(customers.map(c => c.customer.customerId)).size !== ids.length) throw new Error('Duplicate case/customer ID');
  const actual = fs.readdirSync(briefingDir).filter(f => f.endsWith('.json')).sort();
  const orphans = actual.filter(f => !ids.includes(f.replace(/\.json$/, '')));
  if (orphans.length) throw new Error('Briefing JSON without a customer: ' + orphans.join(', '));
  // Metadata is assembled in memory for the existing store, never stored as a
  // second editable briefing. Only briefing-json/*.json is the content source.
  // A customer without a briefing file (null) ships as a snapshot only; the screen shows the briefing as not ready.
  const briefings = customers.map(c => {
    const id = c.briefingMeta.caseId, file = path.join(briefingDir, id + '.json');
    if (!fs.existsSync(file)) return null;
    const content = json(file);
    const errors = contract.validateContent(content, c);
    if (errors.length) throw new Error(id + ': ' + errors.join('\n'));
    return { schemaVersion: contract.version, caseId: id, customerId: c.customer.customerId,
      asOfDate: c.briefingMeta.asOfDate, status: 'draft', title: '고객별 브리핑', ...content };
  });
  if (!briefings.some(Boolean)) throw new Error('No briefing JSON found');
  return { customers, briefings, noBriefing: customers.filter((c, i) => !briefings[i]).map(c => c.briefingMeta.caseId) };
}

// Starroot file code of the deployed business page; pass another code as the CLI argument to override.
const DEFAULT_FILE_CODE = '1288272';

function artifacts(fileCode = DEFAULT_FILE_CODE) {
  if (!/^(REPLACE_WITH_FILE_CODE|\d+)$/.test(fileCode)) throw new Error('File code must be numeric');
  const data = inputs();
  const modules = ['briefing-contract.js', 'pensionCustomerView.js', 'pensionBriefingView.js',
    'pensionBriefingStore.js', 'pensionBriefingAdapter.js', 'fabrix-briefing-contract.js',
    'fabrix-transport.js', 'pensionFabrix.js', 'fabrix-chat-transport.js', 'pensionChat.js', 'pensionAgentDemo.js'];
  const js = '/* Generated by tools/briefing/build.js. Edit source/JSON, not this file. */\n' +
    '(function(window, document) {\nvar module, exports, require;\n' +
    'if (window.__PensionVanilla) window.__PensionVanilla.destroy();\n' +
    // Only customer snapshots ship to the browser; briefing text comes from the Agent.
    'window.PensionBriefingFixtures = ' + JSON.stringify({ customers: data.customers, noBriefing: data.noBriefing }).replace(/</g, '\\u003c') + ';\n' +
    modules.map(f => '\n/* ' + f + ' */\n' + read(path.join(SRC, f))).join('\n;\n')
      .replace("var STARROOT_FILE_CODE = 'REPLACE_WITH_FILE_CODE';", "var STARROOT_FILE_CODE = '" + fileCode + "';") +
    '\n})(window, document);\n';
  const html = read(path.join(SRC, 'mnPensionAgentDemo.html'));
  if ((html.match(/<script\b[^>]*\bsrc=/g) || []).length !== 1 || (html.match(/<link\b/g) || []).length !== 1) throw new Error('HTML must reference one JS and one CSS');
  // The config block ships empty; credentials are filled only in the deployed copy.
  const block = html.match(/window\.__PENSION_FABRIX_CONFIG = window\.__PENSION_FABRIX_CONFIG \|\| \{([\s\S]*?)\n\s*\};/);
  if (!block) throw new Error('FabriX config block not found in HTML');
  for (const [, key, value] of block[1].matchAll(/\b(\w+):\s*('[^']*'|\d+)/g)) {
    if (value !== "''" && value !== '0') throw new Error('FabriX config block must stay empty in source: ' + key);
  }
  return { 'mnPensionAgentDemo.html': html, 'pensionAgentDemo.js': js, 'pensionAgentDemo.css': read(path.join(SRC, 'pensionAgentDemo.css')) };
}

function build(fileCode) {
  fs.mkdirSync(OUT, { recursive: true });
  for (const [name, body] of Object.entries(artifacts(fileCode))) fs.writeFileSync(path.join(OUT, name), body);
  const data = inputs(), first = data.briefings.findIndex(Boolean), req = wire.request(data.customers[first], 'example-request-001', 'TEST_EMPLOYEE');
  fs.writeFileSync(path.join(ROOT, 'integration/contracts/response.example.json'), JSON.stringify(wire.answer(req, contract.contentOf(data.briefings[first])), null, 2) + '\n');
  fs.writeFileSync(path.join(ROOT, 'agent/briefing_data.json'), JSON.stringify(agentData(data)) + '\n');
  console.log('Built frontend (1 HTML + 1 JS + 1 CSS) from ' + data.customers.length + ' customers and Agent data from ' + data.briefings.filter(Boolean).length + ' customer/briefing pairs. Source JSON unchanged.');
}

function agentData(data = inputs()) {
  return { schema_version: wire.version, answer_schema: wire.answerSchema,
    // Only customers with a stored briefing are served by the fixed Agent.
    cases: Object.fromEntries(data.customers.map((customer, i) => [customer.briefingMeta.caseId, data.briefings[i]]).filter(([, b]) => b).map(([id, b], i) => [id,
      { customer_data: data.customers.find(c => c.briefingMeta.caseId === id), briefing: contract.contentOf(b) }])) };
}

function preview() {
  // Static preview only. No fake Agent, mock HTTP endpoint or credential capture.
  const assets = new Map([
    ['/', ['mnPensionAgentDemo.html', 'text/html; charset=utf-8']],
    ['/mnbank/app/js/bfe/pension/pensionAgentDemo.js', ['pensionAgentDemo.js', 'text/javascript; charset=utf-8']],
    ['/mnbank/app/css/bfe/pension/pensionAgentDemo.css', ['pensionAgentDemo.css', 'text/css; charset=utf-8']]
  ]);
  const server = require('http').createServer((req, res) => {
    const asset = assets.get(req.url);
    if (req.method !== 'GET' || !asset) { res.writeHead(404).end(); return; }
    try {
      let body = read(path.join(OUT, asset[0]));
      if (asset[0].endsWith('.html')) {
        const code = read(path.join(OUT, 'pensionAgentDemo.js')).match(/^\s*var STARROOT_FILE_CODE = '([^']+)'/m)[1];
        body = body.replace('</head>', '<style>html{font-size:10px}body{margin:0}</style></head>')
          .replace('</body>', '<script>window[' + JSON.stringify('PG_' + code) + '].onParam({localPreview:true});</script></body>');
      }
      res.writeHead(200, { 'Content-Type': asset[1], 'Cache-Control': 'no-store' }).end(body);
    } catch (_) { res.writeHead(500).end('Build the frontend first.'); }
  });
  server.on('error', err => { console.error('Preview failed: ' + err.code); process.exitCode = 1; });
  server.listen(8765, '127.0.0.1', () => console.log('Static preview: http://127.0.0.1:8765 (no mock API). Ctrl+C to stop.'));
  return server;
}
if (require.main === module) {
  if (process.argv[2] === '--preview') preview();
  else build(process.argv[2] || DEFAULT_FILE_CODE);
}
module.exports = { ROOT, SRC, OUT, ACTIVE, DEFAULT_FILE_CODE, inputs, artifacts, agentData, build };
