/* Development only: editable JSON + vanilla source -> three deployment files. */
'use strict';
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '../..');
const SRC = path.join(ROOT, 'frontend/src/briefing');
const OUT = path.join(ROOT, 'frontend/briefing-fabrix');
const ACTIVE = path.join(ROOT, 'agent-workbench/case-design/active');
const contract = require('../../frontend/src/briefing/briefing-contract');
const wire = require('../../frontend/src/briefing/fabrix-briefing-contract');
const branchData = require('./branch-data');
const read = file => fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n');
const json = file => JSON.parse(read(file));

function inputs() {
  const dataDir = path.join(ACTIVE, 'display-data');
  const customerFiles = fs.readdirSync(dataDir).filter(f => /^B\d{2}-\d{2}\.json$/.test(f)).sort();
  const kim = json(path.join(ROOT, 'agent-workbench/case-design/materials/reference-cases/DEMO-01_KIM_SEOYEON_표시용데이터_v0.1.json'));
  const customers = [kim, ...customerFiles.map(f => {
    const customer = json(path.join(dataDir, f));
    if (customer.briefingMeta.caseId + '.json' !== f) throw new Error('Customer filename/caseId mismatch: ' + f);
    return customer;
  })];
  if (kim.briefingMeta.caseId !== 'DEMO-01') throw new Error('Kim caseId must be DEMO-01');
  const ids = customers.map(c => c.briefingMeta.caseId);
  if (new Set(ids).size !== ids.length || new Set(customers.map(c => c.customer.customerId)).size !== ids.length) throw new Error('Duplicate case/customer ID');
  const actual = fs.readdirSync(path.join(ACTIVE, 'briefing-json')).filter(f => f.endsWith('.json')).sort();
  if (JSON.stringify(actual) !== JSON.stringify(ids.map(id => id + '.json').sort())) throw new Error('Customer/briefing JSON sets do not match');
  // Metadata is assembled in memory for the existing store, never stored as a
  // second editable briefing. Only briefing-json/*.json is the content source.
  const briefings = customers.map(c => {
    const id = c.briefingMeta.caseId, content = json(path.join(ACTIVE, 'briefing-json', id + '.json'));
    const errors = contract.validateContent(content, c);
    if (errors.length) throw new Error(id + ': ' + errors.join('\n'));
    return { schemaVersion: contract.version, caseId: id, customerId: c.customer.customerId,
      asOfDate: c.briefingMeta.asOfDate, status: 'draft', title: '고객별 브리핑', ...content };
  });
  return { customers, briefings };
}

// Starroot file code of the deployed business page; pass another code as the CLI argument to override.
const DEFAULT_FILE_CODE = '1288272';

function artifacts(fileCode = DEFAULT_FILE_CODE, data = inputs(), branch = branchData.generate(data)) {
  if (!/^(REPLACE_WITH_FILE_CODE|\d+)$/.test(fileCode)) throw new Error('File code must be numeric');
  const modules = ['briefing-contract.js', 'pensionCustomerView.js', 'pensionBriefingView.js',
    'pensionBriefingStore.js', 'pensionBriefingAdapter.js', 'fabrix-briefing-contract.js',
    'fabrix-transport.js', 'pensionFabrix.js', 'fabrix-chat-transport.js', 'pensionChat.js',
    // 부점 AI: current main-list search. Core/data/provider/session precede the DOM modules and the adapter.
    'branch-agent-contract.js', 'branch-agent-transport.js', 'branch-search-core.js', 'branch-search-current-data.js', 'branch-search-current-provider.js', 'branch-search-conversation.js', 'branch-search-session.js',
    'branch-search-motion.js', 'branch-search-widget.js', 'branch-search-adapter.js', 'pensionAgentDemo.js'];
  const js = '/* Generated by tools/briefing/build.js. Edit source/JSON, not this file. */\n' +
    '(function(window, document) {\nvar module, exports, require;\n' +
    'if (window.__PensionVanilla) window.__PensionVanilla.destroy();\n' +
    // Schema is exported from Pydantic; the manifest comes from the same projection as the Agent data.
    'window.PensionBranchAgentSchema = ' + JSON.stringify(json(path.join(ROOT, 'integration/contracts/branch-agent.schema.json'))).replace(/</g, '\\u003c') + ';\n' +
    'window.PensionBranchDataManifest = ' + JSON.stringify(branch.manifest).replace(/</g, '\\u003c') + ';\n' +
    // Only customer snapshots ship to the browser; briefing text comes from the Agent.
    'window.PensionBriefingFixtures = ' + JSON.stringify({ customers: data.customers }).replace(/</g, '\\u003c') + ';\n' +
    // Fallback copy of the widget rules: injected only when the deployed pensionAgentDemo.css lacks them (stale/partial CSS deploy).
    'window.PensionBranchSearchStyles = ' + JSON.stringify(read(path.join(SRC, 'branch-search.css'))).replace(/</g, '\\u003c') + ';\n' +
    modules.map(f => '\n/* ' + f + ' */\n' + read(path.join(SRC, f))).join('\n;\n')
      .replace("var STARROOT_FILE_CODE = 'REPLACE_WITH_FILE_CODE';", "var STARROOT_FILE_CODE = '" + fileCode + "';") +
    '\n})(window, document);\n';
  const html = read(path.join(SRC, 'mnPensionAgentDemo.html'));
  if ((html.match(/<script\b[^>]*\bsrc=/g) || []).length !== 1 || (html.match(/<link\b/g) || []).length !== 1) throw new Error('HTML must reference one JS and one CSS');
  // The config block ships empty; credentials are filled only in the deployed copy.
  const block = html.match(/window\.__PENSION_FABRIX_CONFIG = window\.__PENSION_FABRIX_CONFIG \|\| \{([\s\S]*?)\n\s*\};/);
  if (!block) throw new Error('FabriX config block not found in HTML');
  for (const [, key, value] of block[1].matchAll(/\b(\w+):\s*('[^']*'|\d+)/g)) {
    if (value !== "''" && value !== '0') throw new Error('FabriX config block must stay empty in source: ' + key);
  }
  // The original stylesheet stays an exact prefix; branch-search.css only adds #pensionAgentDemo .pad-branch-* rules.
  const css = read(path.join(SRC, 'pensionAgentDemo.css')) + '\n/* branch-search.css */\n' + read(path.join(SRC, 'branch-search.css'));
  return { 'mnPensionAgentDemo.html': html, 'pensionAgentDemo.js': js, 'pensionAgentDemo.css': css };
}

function build(fileCode) {
  const data = inputs(), branch = branchData.generate(data), files = artifacts(fileCode, data, branch);
  fs.mkdirSync(OUT, { recursive: true });
  for (const [name, body] of Object.entries(files)) fs.writeFileSync(path.join(OUT, name), body);
  branchData.write(branch);
  const req = wire.request(data.customers[0], 'example-request-001', 'TEST_EMPLOYEE');
  fs.writeFileSync(path.join(ROOT, 'integration/contracts/response.example.json'), JSON.stringify(wire.answer(req, contract.contentOf(data.briefings[0])), null, 2) + '\n');
  fs.writeFileSync(path.join(ROOT, 'agent/briefing_data.json'), JSON.stringify(agentData(data)) + '\n');
  console.log('Built frontend (1 HTML + 1 JS + 1 CSS) and Agent data from ' + data.customers.length + ' customer/briefing pairs. Source JSON unchanged.');
  console.log('Built branch data/manifest: ' + branch.manifest.record_count + ' rows, data_version=' + branch.manifest.data_version);
}

function agentData(data = inputs()) {
  return { schema_version: wire.version, answer_schema: wire.answerSchema,
    cases: Object.fromEntries(data.customers.map((customer, i) => [customer.briefingMeta.caseId,
      { customer_data: customer, briefing: contract.contentOf(data.briefings[i]) }])) };
}

function preview() {
  // Static preview only. No fake Agent, mock HTTP endpoint or credential capture.
  const assets = new Map([
    ['/', ['mnPensionAgentDemo.html', 'text/html; charset=utf-8']],
    ['/mnbank/app/html/bfe/asstmgt/asst/pensionAgentDemo.js', ['pensionAgentDemo.js', 'text/javascript; charset=utf-8']],
    ['/mnbank/app/html/bfe/asstmgt/asst/pensionAgentDemo.css', ['pensionAgentDemo.css', 'text/css; charset=utf-8']]
  ]);
  const server = require('http').createServer((req, res) => {
    const asset = assets.get(req.url);
    if (req.method !== 'GET' || !asset) { res.writeHead(404).end(); return; }
    try {
      let body = read(path.join(OUT, asset[0]));
      if (asset[0].endsWith('.html')) {
        const code = read(path.join(OUT, 'pensionAgentDemo.js')).match(/^\s*var STARROOT_FILE_CODE = '([^']+)'/m)[1];
        body = body.replace('</head>', '<style>html{font-size:10px}body{margin:0}</style></head>')
          .replace('</body>', '<script>window[' + JSON.stringify('PG_' + code) + '].onParam({localPreview:true});</script></body>');
      }
      res.writeHead(200, { 'Content-Type': asset[1], 'Cache-Control': 'no-store' }).end(body);
    } catch (_) { res.writeHead(500).end('Build the frontend first.'); }
  });
  server.on('error', err => { console.error('Preview failed: ' + err.code); process.exitCode = 1; });
  server.listen(8765, '127.0.0.1', () => console.log('Static preview: http://127.0.0.1:8765 (no mock API). Ctrl+C to stop.'));
  return server;
}
if (require.main === module) {
  if (process.argv[2] === '--preview') preview();
  else build(process.argv[2] || DEFAULT_FILE_CODE);
}
module.exports = { ROOT, SRC, OUT, ACTIVE, DEFAULT_FILE_CODE, inputs, artifacts, agentData, build };
